#!/bin/sh
if [ ! -f /usr/lib/enigma2/python/Components/Task.py.org ]; then
	cp /usr/lib/enigma2/python/Components/Task.py /usr/lib/enigma2/python/Components/Task.py.org
fi
cp  /usr/lib/enigma2/python/Plugins/SystemPlugins/JobCockpit/Components/Task.py /usr/lib/enigma2/python/Components/Task.py

echo "***********************************"
echo "*           JobCockpit            *"
echo "*               by                *"
echo "*          dream-alpha            *"
echo "***********************************"
echo ""
echo "Plugin installed successfully."
echo "Please restart DreamOS now!"
echo ""
exit 0
