#!/bin/sh
if [ "$1" = "remove" ]; then
	rm -rf /usr/lib/enigma2/python/Plugins/SystemPlugins/JobCockpit > /dev/null 2>&1
	cp /usr/lib/enigma2/python/Components/Task.py.org /usr/lib/enigma2/python/Components/Task.py
	echo "JobCockpit plugin removed successfully."
else
	find /usr/lib/enigma2/python/Plugins/SystemPlugins/JobCockpit -type f -name "*.pyo" -exec rm -f {} \; > /dev/null 2>&1
fi
exit 0
